name: Release

on:
  push:
    tags:
      - 'v*' # Trigger on version tags like v0.1.0, v1.2.3

jobs:
  release:
    permissions:
      contents: write # Required to create releases and upload assets
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: aarch64-apple-darwin,x86_64-apple-darwin

      - name: Install root dependencies
        run: bun install

      - name: Install frontend dependencies
        working-directory: forest-desktop
        run: bun install

      - name: Build Tauri app
        working-directory: forest-desktop
        run: bun run tauri build --target universal-apple-darwin
        env:
          TAURI_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}
          TAURI_KEY_PASSWORD: ${{ secrets.TAURI_KEY_PASSWORD }}

      - name: Extract version from tag
        id: version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          name: Forest Desktop v${{ steps.version.outputs.VERSION }}
          draft: false
          prerelease: false
          generate_release_notes: true
          files: |
            forest-desktop/src-tauri/target/universal-apple-darwin/release/bundle/dmg/*.dmg
